<a href="https://colab.research.google.com/github/F1ameX/Modern-Methods-of-Deep-Machine-Learning/blob/main/3_multilayer_perceptron/3_multilayer_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Modules

In [ ]:
import numpy as np
import pandas as pd
import torch
from torch import nn
from numpy.typing import ArrayLike
from tqdm.notebook import tqdm

## Distribution

In [ ]:
def make_circles(n_samples : int = 100,
                 shuffle : bool = True,
                 noise : float = None,
                 random_state : int = None,
                 factor : float = 0.8):

    rng = np.random.default_rng(seed = random_state)

    n_samples_out = n_samples // 2
    n_samples_in = n_samples - n_samples_out

    linspace_out = np.linspace(0, 2 * np.pi, n_samples_out, endpoint = False)
    linspace_in = np.linspace(0, 2 * np.pi, n_samples_in, endpoint = False)

    X1_out = np.cos(linspace_out) * 5
    X2_out = np.sin(linspace_out) * 5

    X1_in = np.cos(linspace_in) * 5 * factor
    X2_in = np.sin(linspace_in) * 5 * factor

    X = np.vstack(
        [np.append(X1_out, X1_in), np.append(X2_out, X2_in)]
    ).T

    y = np.hstack (
        [np.zeros(n_samples_out, dtype = int), np.ones(n_samples_in, dtype = int)]
    )

    if noise is not None:
        X += rng.normal(scale = noise, size = X.shape)

    if shuffle:
        permutation = rng.permutation(n_samples)
        X = X[permutation]
        y = y[permutation]

    return X, y


def make_xor(n_samples : int = 100,
             noise : float = 0.2,
             scale : float = 1.0,
             centers : ArrayLike | None = None,
             shuffle : bool = True,
             random_state : int = 42,
             return_centers : bool = False):

    rng = np.random.default_rng(seed = random_state)

    if centers is None:
        centers = np.array(
            [
                (scale, scale),
                (scale, -scale),
                (-scale, scale),
                (-scale, -scale),
             ],
            dtype = float
            )

    n_centers = centers.shape[0]

    base = n_samples // n_centers
    extra = n_samples % n_centers

    clusters = np.zeros(n_centers, dtype = int)

    for k in range(n_centers):
        if k < extra:
            clusters[k] = base + 1
        else:
            clusters[k] = base

    X = np.empty((n_samples, 2))
    y = np.empty(n_samples, dtype = int)

    pos = 0
    for k in range(n_centers):
        normal_matrix = rng.normal(loc = 0, scale = 1, size = (clusters[k], 2))
        X_k = centers[k] + noise * normal_matrix

        if k in [0, 3]:
            y[pos : pos + clusters[k]] = 0
        else:
            y[pos : pos + clusters[k]] = 1

        X[pos : pos + clusters[k]] = X_k
        pos += clusters[k]

    if shuffle:
        permutation = rng.permutation(n_samples)
        X = X[permutation]
        y = y[permutation]

    if return_centers:
        return X, y, centers
    return X, y


def make_blobs(n_samples : int = 100,
               n_features : int = 2,
               centers : int | ArrayLike | None = None,
               cluster_std : float | ArrayLike = 1.0,
               center_box : tuple[float, float] = (-1.0, 1.0),
               shuffle : bool = True,
               random_state : int = 42,
               return_centers : bool = False):

    rng = np.random.default_rng(seed = random_state)

    if centers is None:
        n_centers = 2

        centers = rng.uniform(
            center_box[0], center_box[1], size = (n_centers, n_features)
        )

    elif isinstance(centers, int):
        n_centers = centers
        centers = rng.uniform(
            center_box[0], center_box[1], size = (n_centers, n_features)
        )

    else:
        centers = np.asarray(centers, dtype = float)
        n_centers = centers.shape[0]

    base = n_samples // n_centers
    extra = n_samples % n_centers

    clusters = np.zeros(n_centers, dtype = int)

    for k in range(n_centers):
        if k < extra:
            clusters[k] = base + 1
        else:
            clusters[k] = base

    if isinstance(cluster_std, int | float):
        cluster_std_sigma = cluster_std
        cluster_std = np.repeat(cluster_std_sigma, n_centers)

    X = np.empty((n_samples, n_features))
    y = np.empty(n_samples, dtype = int)

    pos = 0

    for k in range(n_centers):
        normal_matrix = rng.normal(loc = 0, scale = 1, size = (clusters[k], n_features))
        X_k = centers[k] + cluster_std[k] * normal_matrix

        y[pos : pos + clusters[k]] = k
        X[pos : pos + clusters[k]] = X_k
        pos += clusters[k]

    if shuffle:
        permutation = rng.permutation(n_samples)
        X = X[permutation]
        y = y[permutation]

    if return_centers:
        return X, y, centers

    return X, y


def make_spiral(n_samples : int = 100,
                turns : int = 2,
                radius : float = 0.0,
                sweep : float = 0.15,
                shuffle : bool = True,
                noise : float = None,
                random_state : int = 42):

    rng = np.random.default_rng(seed = random_state)

    n_samples_out = n_samples // 2
    n_samples_in = n_samples - n_samples_out

    theta_out = np.linspace(0, turns * 2 * np.pi, n_samples_out, endpoint = False)
    theta_in = np.linspace(0, turns * 2 * np.pi, n_samples_in, endpoint = False)

    spiral_out = radius + sweep * theta_out
    spiral_in = radius + sweep * theta_in

    X1_out = spiral_out * np.cos(theta_out)
    X2_out = spiral_out * np.sin(theta_out)

    X1_in = spiral_in * np.cos(theta_in + np.pi)
    X2_in = spiral_in * np.sin(theta_in + np.pi)

    X = np.vstack(
        [np.append(X1_out, X1_in), np.append(X2_out, X2_in)]
    ).T

    y = np.hstack(
        [np.zeros(n_samples_out, dtype = int), np.ones(n_samples_in, dtype = int)]
    )

    if noise is not None:
        X += rng.normal(scale = noise, size = X.shape)

    if shuffle:
        permutation = rng.permutation(n_samples)
        X = X[permutation]
        y = y[permutation]

    return X, y


def split_data(X: np.array, y: np.array, ratio: float = 0.30, random_state: int = 42):
    rng = np.random.default_rng(seed=random_state)
    idx = np.arange(X.shape[0])
    rng.shuffle(idx)
    left_share = int((1 - ratio) * X.shape[0])

    train_idx = idx[:left_share]
    test_idx  = idx[left_share:]

    return train_idx, test_idx

## MLP

In [ ]:
class MultiLayerPerceptron(nn.Module):
    def __init__(self,
                 activation : str = 'sigmoid',
                 layers : int = 4,
                 neurons : int = 3,
                 task : str = 'classification'):

        super().__init__()
        assert activation in ['sigmoid', 'tanh', 'relu']
        assert task in ['classification', 'regression']
        self.task = task

        activation_function = {
            'sigmoid' : nn.Sigmoid,
            'tanh' : nn.Tanh,
            'relu' : nn.ReLU,
        }[activation]

        self.loss_function = {
            'classification' : nn.BCELoss(),
            'regression' : nn.MSELoss(),
        }[task]

        dims = [2] + [neurons] * (layers) + [1]

        modules = []
        for i in range(len(dims) - 1):
            modules.append(nn.Linear(dims[i], dims[i + 1]))
            if i != len(dims) - 2:
                modules.append(activation_function())
            else:
                if task == 'classification':
                    modules.append(nn.Sigmoid())

        self.network = nn.Sequential(*modules)

    def forward(self, X) -> torch.Tensor:
        preds = self.network(X)
        return preds

    def fit(self,
            X: torch.Tensor,
            y: torch.Tensor,
            learning_rate : float = 0.01,
            n_epochs : int = 100,
            batch_size : int = 16,
            random_state : int = 42,
            ):
        rng = np.random.default_rng(seed = random_state)

        y = y.reshape(-1, 1)

        _X = X.clone()
        _y = y.clone()

        optimizer = torch.optim.Adam(self.parameters(), lr = learning_rate)

        for epoch in tqdm(
                range(n_epochs),
                desc = "Fitting MLP",
                unit = "epoch",
                total = n_epochs,
                dynamic_ncols = True,
                leave = True,
                mininterval = 0.1,
                disable = True):

            self.train()
            permutation = rng.permutation(X.shape[0])
            _X = X.clone()[permutation]
            _y = y.clone()[permutation]

            for batch_start in range(0, X.shape[0], batch_size):
                _X_batch = _X[batch_start : batch_start + batch_size]
                _y_batch = _y[batch_start : batch_start + batch_size]

                preds = self(_X_batch)
                loss = self.loss_function(preds, _y_batch)

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

        return self

    def predict(self, X: torch.Tensor) -> torch.Tensor:
        self.eval()
        with torch.no_grad():

            if self.task == 'classification':
                prob = self(X)
                pred = (prob >= 0.5).to(torch.float64)
                return pred

            elif self.task == 'regression':
                pred = self(X)
                return pred.to(torch.float64)

## Fitting part

In [ ]:
def build_architecture_tables(X : np.array,
                              y : np.array,
                              task : str = 'classification') -> None:

    train_idx, test_idx = split_data(X, y, ratio = 0.25, random_state = 52)
    X_train, y_train = X[train_idx], y[train_idx]
    X_test, y_test = X[test_idx], y[test_idx]

    X_train = torch.from_numpy(X_train).type(torch.FloatTensor)
    y_train = torch.from_numpy(y_train).type(torch.FloatTensor).view(-1, 1)
    X_test = torch.from_numpy(X_test).type(torch.FloatTensor)
    y_test = torch.from_numpy(y_test).type(torch.FloatTensor).view(-1, 1)

    for activation in ['sigmoid', 'tanh', 'relu']:
        stat_table = pd.DataFrame(columns = list(range(1, 6)),
                                index = list(range(2, 5)))

        stat_table.index.name = "Layers"
        stat_table.columns.name = "Neurons"

        for layers in range(2, 5):
            for neurons in range(1, 6):
                model = MultiLayerPerceptron(activation = activation,
                                            layers = layers,
                                            neurons = neurons,
                                            task = task)
                model.fit(X_train, y_train,
                        learning_rate = 0.01,
                        n_epochs = 500,
                        batch_size = 25,
                        random_state = 52)

                if task == 'classification':
                    metric = 'accuracy'
                    accuracy = round((model.predict(X_test) == y_test).float().mean().item(), 3)
                    stat_table.loc[layers, neurons] = accuracy
                elif task == 'regression':
                    metric = 'MSE'
                    mse = round(((y_test - model.predict(X_test))**2).float().mean().item(), 3)
                    stat_table.loc[layers, neurons] = mse

        print(f"Таблица {metric} для функции активации {activation}")
        display(stat_table)
        print('\n\n')

### Classification part

In [ ]:
print('=' * 25 + ' Концентрические окружности ' + '=' * 25)
X, y = make_circles(n_samples = 500, noise = 0.5, factor = 0.25, random_state = 52)
build_architecture_tables(X, y, task = 'classification')
print('=' * 78)

print('=' * 25 + ' Гауссовские кластеры ' + '=' * 25)
X, y = make_blobs(n_samples = 500, centers = [-2.5, 2.5], cluster_std = 1.2)
build_architecture_tables(X, y, task = 'classification')
print('=' * 72 + '\n\n')

print('=' * 25 + ' XOR распределение ' + '=' * 25)
X, y = make_xor(n_samples = 500, scale = 2.75, noise = 1.0)
build_architecture_tables(X, y, task = 'classification')
print('=' * 69 + '\n\n')

print('=' * 25 + ' Спирали Архимеда ' + '=' * 25)
X, y = make_spiral(n_samples = 500, sweep = 0.25, turns = 3.5, noise = 0.1, radius = 0.05)
build_architecture_tables(X, y, task = 'classification')
print('=' * 68 + '\n\n')

========================= Концентрические окружности =========================
Таблица accuracy для функции активации sigmoid

Neurons      1     2      3    4    5
Layers
2        0.664  0.84  0.712  1.0  1.0
3        0.664  0.88    1.0  1.0  1.0
4        0.648  0.84    1.0  1.0  1.0

Таблица accuracy для функции активации tanh

Neurons      1      2    3    4    5
Layers
2         0.72   0.88  1.0  1.0  1.0
3        0.672  0.832  1.0  1.0  1.0
4        0.496   0.88  1.0  1.0  1.0

Таблица accuracy для функции активации relu

Neurons      1      2      3    4    5
Layers
2         0.72   0.88    1.0  1.0  1.0
3        0.496  0.952    1.0  1.0  1.0
4        0.496  0.936  0.496  1.0  1.0

==============================================================================
========================= Гауссовские кластеры =========================
Таблица accuracy для функции активации sigmoid

Neurons      1      2      3      4      5
Layers
2        0.984  0.984  0.976  0.976  0.976
3        0.984  0.984  0.984  0.976  0.976
4        0.984  0.968  0.984  0.976  0.976

Таблица accuracy для функции активации tanh

Neurons      1      2      3      4      5
Layers
2        0.984  0.984  0.984  0.976  0.976
3        0.984  0.976  0.976  0.976  0.976
4        0.984  0.992  0.976  0.976  0.984

Таблица accuracy для функции активации relu

Neurons      1      2      3      4      5
Layers
2        0.432  0.984  0.984  0.968  0.976
3        0.432  0.984  0.432  0.976  0.968
4        0.432  0.432  0.984  0.976  0.976

========================================================================


========================= XOR распределение =========================
Таблица accuracy для функции активации sigmoid

Neurons      1      2      3      4      5
Layers
2        0.672  0.944  0.688    1.0    1.0
3        0.664  0.752  0.992  0.688  0.992
4        0.736  0.744   0.96    1.0  0.992

Таблица accuracy для функции активации tanh

Neurons      1      2    3      4      5
Layers
2        0.776   0.96  1.0  0.992  0.992
3        0.784  0.688  1.0    1.0    1.0
4        0.728  0.752  1.0    1.0    1.0

Таблица accuracy для функции активации relu

Neurons      1      2      3      4    5
Layers
2        0.744  0.752    1.0  0.688  1.0
3         0.44  0.976  0.992    1.0  1.0
4         0.72   0.44   0.68    1.0  1.0

=====================================================================


========================= Спирали Архимеда =========================
Таблица accuracy для функции активации sigmoid

Neurons      1      2      3      4      5
Layers
2        0.432  0.432  0.432  0.424  0.496
3        0.432   0.52  0.432  0.432  0.432
4        0.504  0.504  0.504  0.512  0.424

Таблица accuracy для функции активации tanh

Neurons      1      2      3      4      5
Layers
2        0.432  0.432   0.52   0.48  0.496
3        0.432  0.432   0.44  0.472  0.536
4        0.432  0.432  0.432  0.536  0.496

Таблица accuracy для функции активации relu

Neurons      1      2      3      4      5
Layers
2        0.512   0.52  0.456  0.528   0.48
3        0.432  0.432  0.496  0.544  0.464
4        0.432  0.432   0.48  0.504  0.584

====================================================================

### Regression part

In [ ]:
print('=' * 25 + ' Концентрические окружности ' + '=' * 25)
X, y = make_circles(n_samples = 500, noise = 0.5, factor = 0.25, random_state = 52)
build_architecture_tables(X, y, task = 'regression')
print('=' * 78)

print('=' * 25 + ' Гауссовские кластеры ' + '=' * 25)
X, y = make_blobs(n_samples = 500, centers = [-2.5, 2.5], cluster_std = 1.2)
build_architecture_tables(X, y, task = 'regression')
print('=' * 72 + '\n\n')

print('=' * 25 + ' XOR распределение ' + '=' * 25)
X, y = make_xor(n_samples = 500, scale = 2.75, noise = 1.0)
build_architecture_tables(X, y, task = 'regression')
print('=' * 69 + '\n\n')

print('=' * 25 + ' Спирали Архимеда ' + '=' * 25)
X, y = make_spiral(n_samples = 500, sweep = 0.25, turns = 3.5, noise = 0.1, radius = 0.05)
build_architecture_tables(X, y, task = 'regression')
print('=' * 68 + '\n\n')

========================= Концентрические окружности =========================
Таблица MSE для функции активации sigmoid

Neurons      1      2      3      4     5
Layers
2        0.207  0.125  0.006  0.007  0.01
3        0.205  0.202    0.0  0.001   0.0
4        0.192  0.122    0.0  0.205   0.0

Таблица MSE для функции активации tanh

Neurons      1      2      3      4      5
Layers
2        0.193    0.1  0.001  0.001  0.006
3        0.202  0.126  0.007    0.0    0.0
4        0.186  0.094    0.0    0.0    0.0

Таблица MSE для функции активации relu

Neurons      1      2     3      4    5
Layers
2        0.202  0.126   0.0  0.004  0.0
3         0.25  0.127  0.25    0.0  0.0
4         0.25  0.115  0.25  0.001  0.0

==============================================================================
========================= Гауссовские кластеры =========================
Таблица MSE для функции активации sigmoid

Neurons      1      2      3      4      5
Layers
2        0.012  0.011  0.012  0.011  0.012
3        0.014  0.012  0.012  0.013  0.016
4        0.014  0.014  0.014  0.017  0.031

Таблица MSE для функции активации tanh

Neurons      1      2      3      4      5
Layers
2        0.014  0.014  0.013  0.015  0.013
3        0.014  0.015  0.025  0.018  0.009
4        0.015  0.019  0.022  0.024  0.027

Таблица MSE для функции активации relu

Neurons      1      2      3      4      5
Layers
2        0.253  0.007   0.02  0.032  0.009
3        0.251  0.011  0.016  0.014  0.021
4        0.254  0.253  0.015  0.032  0.011

========================================================================


========================= XOR распределение =========================
Таблица MSE для функции активации sigmoid

Neurons      1      2      3      4      5
Layers
2        0.165  0.038  0.153  0.001  0.002
3        0.185  0.038    0.0    0.0  0.004
4        0.199  0.148  0.008  0.008    0.0

Таблица MSE для функции активации tanh

Neurons      1      2    3      4    5
Layers
2        0.185  0.038  0.0    0.0  0.0
3        0.185  0.151  0.0    0.0  0.0
4        0.167  0.036  0.0  0.002  0.0

Таблица MSE для функции активации relu

Neurons      1      2      3      4    5
Layers
2        0.166  0.174  0.002    0.0  0.0
3        0.166  0.253  0.016    0.0  0.0
4        0.201  0.154    0.0  0.148  0.0

=====================================================================


========================= Спирали Архимеда =========================
Таблица MSE для функции активации sigmoid

Neurons      1      2      3      4      5
Layers
2        0.262  0.258  0.269   0.26   0.27
3        0.266  0.266  0.266  0.266  0.266
4        0.266  0.256  0.257  0.255  0.255

Таблица MSE для функции активации tanh

Neurons      1      2      3      4      5
Layers
2        0.262  0.262   0.27   0.28  0.268
3        0.248  0.263  0.295  0.275  0.252
4        0.256  0.271  0.269  0.226  0.268

Таблица MSE для функции активации relu

Neurons      1      2      3      4      5
Layers
2        0.251  0.259   0.26  0.259  0.282
3        0.251  0.251  0.277  0.268  0.259
4        0.251  0.253  0.253  0.263  0.251

====================================================================

## Cross-Validation

In [ ]:
train_fracs = np.arange(0.05, 1.00, 0.05)
target = 0.90

datasets = {
    'circles' : make_circles(n_samples = 500, noise = 0.5, factor = 0.25, random_state = 52),
    'blobs' :   make_blobs(n_samples = 500, centers = [-2.5, 2.5], cluster_std = 1.2),
    'xor' :     make_xor(n_samples = 500, scale = 2.75, noise = 1.0),
    'spiral' :  make_spiral(n_samples = 500, sweep = 0.25, turns = 3.5, noise = 0.1, radius = 0.05),
}

summary_rows = []
curves = {}

for name, (X, y) in datasets.items():
    X = np.asarray(X, dtype=np.float32)
    y = np.asarray(y, dtype=np.float32)

    curve_rows = []
    best_frac = None

    for train_frac in train_fracs:
        test_frac = 1.0 - float(train_frac)

        train_idx, test_idx = split_data(X, y, ratio=test_frac, random_state=52)

        X_train = torch.from_numpy(X[train_idx]).float()
        y_train = torch.from_numpy(y[train_idx]).float().view(-1, 1)
        X_test  = torch.from_numpy(X[test_idx]).float()
        y_test  = torch.from_numpy(y[test_idx]).float().view(-1, 1)

        model = MultiLayerPerceptron(activation="tanh", layers=3,
                                     neurons=5, task="classification")

        model.fit(X_train, y_train, learning_rate=0.01, n_epochs=500,
                  batch_size=25, random_state=52)

        acc = (model.predict(X_test) == y_test).float().mean().item()
        curve_rows.append((train_frac, acc))

        if best_frac is None and acc >= target:
            best_frac = train_frac

    curves[name] = pd.DataFrame(curve_rows, columns=["train_frac", "test_acc"]).set_index("train_frac")

    summary_rows.append({
        "dataset": name,
        "best_train_frac": best_frac,
        "best_train_size": None if best_frac is None else int(round(best_frac * len(X))),
        "target_acc": target,
    })

summary_df = pd.DataFrame(summary_rows).set_index("dataset")
display(summary_df)

for name, df_curve in curves.items():
    print(f"\n===== {name.upper()} =====")
    display(df_curve)

         best_train_frac  best_train_size  target_acc
dataset
circles             0.15             75.0         0.9
blobs               0.05             25.0         0.9
xor                 0.05             25.0         0.9
spiral               NaN              NaN         0.9

===== CIRCLES =====

            test_acc
train_frac
0.05        0.827368
0.10        0.869180
0.15        1.000000
0.20        1.000000
0.25        1.000000
0.30        1.000000
0.35        1.000000
0.40        1.000000
0.45        1.000000
0.50        1.000000
0.55        1.000000
0.60        1.000000
0.65        1.000000
0.70        1.000000
0.75        1.000000
0.80        1.000000
0.85        1.000000
0.90        1.000000
0.95        1.000000

===== BLOBS =====

            test_acc
train_frac
0.05        0.993684
0.10        0.993348
0.15        0.992941
0.20        0.990025
0.25        0.989333
0.30        0.980000
0.35        0.993846
0.40        0.990000
0.45        0.989130
0.50        0.992000
0.55        0.986667
0.60        0.990000
0.65        0.988571
0.70        0.980000
0.75        0.976000
0.80        0.990000
0.85        1.000000
0.90        1.000000
0.95        1.000000

===== XOR =====

            test_acc
train_frac
0.05        0.978947
0.10        0.995565
0.15        0.981176
0.20        0.972569
0.25        0.992000
0.30        0.991429
0.35        1.000000
0.40        0.993333
0.45        0.996377
0.50        1.000000
0.55        1.000000
0.60        0.995000
0.65        0.994286
0.70        0.993333
0.75        1.000000
0.80        1.000000
0.85        1.000000
0.90        1.000000
0.95        1.000000

===== SPIRAL =====

            test_acc
train_frac
0.05        0.513684
0.10        0.518847
0.15        0.510588
0.20        0.548628
0.25        0.525333
0.30        0.551429
0.35        0.538462
0.40        0.506667
0.45        0.510870
0.50        0.564000
0.55        0.533333
0.60        0.565000
0.65        0.480000
0.70        0.520000
0.75        0.504000
0.80        0.530000
0.85        0.546667
0.90        0.620000
0.95        0.520000

In [ ]:
def kfold_indices(n_samples: int, k: int = 5, seed: int = 52):
    rng = np.random.default_rng(seed)
    idx = rng.permutation(n_samples)
    folds = np.array_split(idx, k)
    return folds


def cv_grid_search_mlp(
    X: np.ndarray,
    y: np.ndarray,
    *,
    k: int = 5,
    seed: int = 52,
    neurons_fixed: int = 5,
    layers_grid=(2, 3, 4),
    activations=("sigmoid", "tanh", "relu"),
    learning_rate: float = 0.01,
    n_epochs: int = 500,
    batch_size: int = 25,
    random_state_fit: int = 52,
    verbose: bool = True,
):
    X = np.asarray(X, dtype=np.float32)
    y = np.asarray(y, dtype=np.float32).reshape(-1)

    folds = kfold_indices(len(X), k=k, seed=seed)

    rows = []
    for activation in activations:
        for layers in layers_grid:
            accs = []
            for fold_id in range(k):
                val_idx = folds[fold_id]
                train_idx = np.concatenate([folds[i] for i in range(k) if i != fold_id])

                X_train = torch.from_numpy(X[train_idx]).float()
                y_train = torch.from_numpy(y[train_idx]).float().view(-1, 1)
                X_val = torch.from_numpy(X[val_idx]).float()
                y_val = torch.from_numpy(y[val_idx]).float().view(-1, 1)

                model = MultiLayerPerceptron(
                    activation = activation,
                    layers = layers,
                    neurons = neurons_fixed,
                    task = "classification",
                )

                model.fit(
                    X_train,
                    y_train,
                    learning_rate=learning_rate,
                    n_epochs=n_epochs,
                    batch_size=batch_size,
                    random_state=random_state_fit,
                )

                acc = (model.predict(X_val) == y_val).float().mean().item()
                accs.append(acc)

            accs = np.array(accs, dtype=float)
            mean_acc = float(accs.mean())
            std_acc = float(accs.std(ddof=1)) if k > 1 else 0.0
            min_acc = float(accs.min())

            rows.append(
                {
                    "activation": activation,
                    "layers": int(layers),
                    "neurons": int(neurons_fixed),
                    "cv_mean_acc": mean_acc,
                    "cv_std_acc": std_acc,
                    "cv_min_acc": min_acc,
                }
            )

            if verbose:
                print(
                    f"activation={activation}, layers={layers}, neurons={neurons_fixed} -> "
                    f"mean={mean_acc:.4f}, std={std_acc:.4f}, min={min_acc:.4f}"
                )

    details_df = pd.DataFrame(rows).sort_values(
        by=["activation", "layers"],
        ascending=[True, True],
    ).reset_index(drop=True)

    best_row = (
        pd.DataFrame(rows)
        .sort_values(by=["cv_mean_acc", "cv_min_acc"], ascending=False)
        .iloc[0]
        .to_dict()
    )
    return details_df, best_row


def cv_for_datasets(
    datasets: dict,
    *,
    k: int = 5,
    seed: int = 52,
    neurons_fixed: int = 5,
    layers_grid = (2, 3, 4),
    activations = ("sigmoid", "tanh", "relu"),
    learning_rate: float = 0.01,
    n_epochs: int = 500,
    batch_size: int = 25,
    random_state_fit: int = 52,
    verbose: bool = True,
):
    summary_rows = []
    all_details = {}

    for name, (X, y) in datasets.items():
        if verbose:
            print(f"\n===== {name.upper()} =====")

        details_df, best = cv_grid_search_mlp(
            X,
            y,
            k=k,
            seed=seed,
            neurons_fixed=neurons_fixed,
            layers_grid=layers_grid,
            activations=activations,
            learning_rate=learning_rate,
            n_epochs=n_epochs,
            batch_size=batch_size,
            random_state_fit=random_state_fit,
            verbose=verbose,
        )
        all_details[name] = details_df

        summary_rows.append(
            {
                "dataset": name,
                "best_activation": best["activation"],
                "best_layers": int(best["layers"]),
                "neurons_fixed": int(best["neurons"]),
                "cv_mean_acc": float(best["cv_mean_acc"]),
                "cv_std_acc": float(best["cv_std_acc"]),
                "cv_min_acc": float(best["cv_min_acc"]),
                "k_folds": int(k),
            }
        )

    summary_df = pd.DataFrame(summary_rows).set_index("dataset")
    return summary_df, all_details


datasets = {}

X_c, y_c = make_circles(n_samples=500, noise=0.5, factor=0.25, random_state=52)
datasets["circles"] = (X_c, y_c)

X_b, y_b = make_blobs(n_samples=500, centers=[-2.5, 2.5], cluster_std=1.2)
datasets["blobs"] = (X_b, y_b)

X_x, y_x = make_xor(n_samples=500, scale=2.75, noise=1.0)
datasets["xor"] = (X_x, y_x)

X_s, y_s = make_spiral(n_samples=500, sweep=0.25, turns=3.5, noise=0.1, radius=0.05)
datasets["spiral"] = (X_s, y_s)

summary_df, all_details = cv_for_datasets(
    datasets,
    k = 5,
    seed = 52,
    neurons_fixed = 5,
    layers_grid = (2, 3, 4),
    activations = ("sigmoid", "tanh", "relu"),
    learning_rate = 0.01,
    n_epochs = 500,
    batch_size = 25,
    random_state_fit = 52,
    verbose = True,
)

display(summary_df)
display(all_details["circles"])

===== CIRCLES =====
activation=sigmoid, layers=2, neurons=5 -> mean=1.0000, std=0.0000, min=1.0000
activation=sigmoid, layers=3, neurons=5 -> mean=0.8600, std=0.1918, min=0.6400
activation=sigmoid, layers=4, neurons=5 -> mean=1.0000, std=0.0000, min=1.0000
activation=tanh, layers=2, neurons=5 -> mean=0.9980, std=0.0045, min=0.9900
activation=tanh, layers=3, neurons=5 -> mean=1.0000, std=0.0000, min=1.0000
activation=tanh, layers=4, neurons=5 -> mean=1.0000, std=0.0000, min=1.0000
activation=relu, layers=2, neurons=5 -> mean=1.0000, std=0.0000, min=1.0000
activation=relu, layers=3, neurons=5 -> mean=1.0000, std=0.0000, min=1.0000
activation=relu, layers=4, neurons=5 -> mean=0.8940, std=0.2370, min=0.4700

===== BLOBS =====
activation=sigmoid, layers=2, neurons=5 -> mean=0.9920, std=0.0045, min=0.9900
activation=sigmoid, layers=3, neurons=5 -> mean=0.9920, std=0.0045, min=0.9900
activation=sigmoid, layers=4, neurons=5 -> mean=0.9900, std=0.0071, min=0.9800
activation=tanh, layers=2, neurons=5 -> mean=0.9880, std=0.0084, min=0.9800
activation=tanh, layers=3, neurons=5 -> mean=0.9880, std=0.0084, min=0.9800
activation=tanh, layers=4, neurons=5 -> mean=0.9860, std=0.0114, min=0.9700
activation=relu, layers=2, neurons=5 -> mean=0.9880, std=0.0084, min=0.9800
activation=relu, layers=3, neurons=5 -> mean=0.9880, std=0.0110, min=0.9800
activation=relu, layers=4, neurons=5 -> mean=0.9900, std=0.0100, min=0.9800

===== XOR =====
activation=sigmoid, layers=2, neurons=5 -> mean=0.9920, std=0.0084, min=0.9800
activation=sigmoid, layers=3, neurons=5 -> mean=0.9960, std=0.0055, min=0.9900
activation=sigmoid, layers=4, neurons=5 -> mean=0.9380, std=0.1277, min=0.7100
activation=tanh, layers=2, neurons=5 -> mean=0.9960, std=0.0055, min=0.9900
activation=tanh, layers=3, neurons=5 -> mean=0.9960, std=0.0055, min=0.9900
activation=tanh, layers=4, neurons=5 -> mean=0.9940, std=0.0089, min=0.9800
activation=relu, layers=2, neurons=5 -> mean=0.9440, std=0.1197, min=0.7300
activation=relu, layers=3, neurons=5 -> mean=0.9960, std=0.0089, min=0.9800
activation=relu, layers=4, neurons=5 -> mean=0.9960, std=0.0055, min=0.9900

===== SPIRAL =====
activation=sigmoid, layers=2, neurons=5 -> mean=0.4700, std=0.0292, min=0.4300
activation=sigmoid, layers=3, neurons=5 -> mean=0.4420, std=0.0217, min=0.4100
activation=sigmoid, layers=4, neurons=5 -> mean=0.5480, std=0.0522, min=0.4800
activation=tanh, layers=2, neurons=5 -> mean=0.4840, std=0.0550, min=0.4200
activation=tanh, layers=3, neurons=5 -> mean=0.4800, std=0.0587, min=0.4000
activation=tanh, layers=4, neurons=5 -> mean=0.6060, std=0.0702, min=0.5300
activation=relu, layers=2, neurons=5 -> mean=0.4940, std=0.0811, min=0.4000
activation=relu, layers=3, neurons=5 -> mean=0.5620, std=0.0881, min=0.4600
activation=relu, layers=4, neurons=5 -> mean=0.6140, std=0.0615, min=0.5100

,best_activation,best_layers,neurons_fixed,cv_mean_acc,cv_std_acc,cv_min_acc,k_folds
dataset,,,,,,,
circles,sigmoid,2,5,1.000,0.000000,1.00,5
blobs,sigmoid,2,5,0.992,0.004472,0.99,5
xor,sigmoid,3,5,0.996,0.005477,0.99,5
spiral,relu,4,5,0.614,0.061482,0.51,5

  activation  layers  neurons  cv_mean_acc  cv_std_acc  cv_min_acc
0       relu       2        5        1.000    0.000000        1.00
1       relu       3        5        1.000    0.000000        1.00
2       relu       4        5        0.894    0.237023        0.47
3    sigmoid       2        5        1.000    0.000000        1.00
4    sigmoid       3        5        0.860    0.191833        0.64
5    sigmoid       4        5        1.000    0.000000        1.00
6       tanh       2        5        0.998    0.004472        0.99
7       tanh       3        5        1.000    0.000000        1.00
8       tanh       4        5        1.000    0.000000        1.00